### ISSUE TITLE
wx.SplashScreen Error

### ISSUE THREAD

**Issue by jhkim07** [cascremers/scyther#15] opened 2017-02-22 14:59 UTC
I am using macOS Sierra and installed wxpython-3.0.2.0, graphviz-2.40.1, and python 2.7.
When I run >>python scyther-gui.py, the following error comes up.
========
Traceback (most recent call last):
  File "scyther-gui.py", line 141, in <module>
    class MySplashScreen(wx.SplashScreen):
AttributeError: 'module' object has no attribute 'SplashScreen'
========

Could you help me resolve this problem?

**Comment by urbangemz** [comment] 2018-01-14 00:24
I get this same issue on os x el capitan

**Comment by gaizka64** [comment] 2018-03-23 08:36
Me too. I read somewhere that it could be because we installed a bad version of wxPython. I tried using 'pip', using 'brew' but didn't manage....

**Comment by Yueneko29** [comment] 2018-04-11 08:16
I got this same error at the first time
After I re-installed then it can work
I use windows 10 and installed python2.7 、 graphviz 0.8.2 and wxPython 4.0.1
But i still don't know what's the problem

**Comment by cascremers** [comment] 2018-04-11 09:52
It seems this is caused by a change in wxPython that is not backwards compatible, see e.g.:

https://stackoverflow.com/questions/17844032/wx-splashscreen-doesnt-work

Using an older version of wxPython (2.6/2.7) might solve this, but Scyther needs an explicit check for wxPython versions to let the user know what the problem is. Ideally, we move to a newer version of wxPython, but this might involve more substantial changes.

**Comment by amgamundani** [comment] 2018-06-07 22:07
Has there been any solution found for this problem yet as I am stuck on Mac OS Sierra 10.13

**Comment by shahnewazsakib** [comment] 2018-10-30 19:57
I had this issue as well. You need to use **wx.adv.SplashScreen** instead of **wx.SplashScreen** and import **wx.adv** as well.

**Comment by cascremers** [comment] 2018-11-09 18:29
Hi all,

Thanks for the comments. I hope to find the time soon to fix this.
Ultimately it is down to wxPython not being backwards compatible; ideally
we should fix Scyther to work with the most recent versions of wxPython (as
well as Python 3), but it is a little bit of work to do so. I'd be very
open to patches/pull requests that fix this!

Best,

Cas

**Comment by maerten** [comment] 2018-11-10 10:02
@Thomas-Fleming's changes fixed it for me (running macOS Mojave and installed wxPython via `pip`)

I couldnt scyther from source so I've copied the files in `/Gui/*` and `/scyther-gui.py` to the `scyther-mac-v1.1.3` distribution.

**Comment by JIAZHEN** [comment] 2019-02-18 10:22
Agreed. With @Thomas-Fleming 's PR I've got ScytherTool working (macOS Mojave and wxPython with pip)

**Comment by cascremers** [comment] 2020-10-28 14:25
This should all be fixed in the `python3-wxpython4` branch soon.

**Closed** 2023-02-12 21:53 UTC
